files:
  - source: /top_speed_net/languages/client/messages.pot
    translation: /top_speed_net/languages/client/%locale%/messages.po
    skip_untranslated_files: true
    languages_mapping:
      locale:
        zh: zh-cn
        zh-CN: zh-cn
        es: es
        es-ES: es
        vi: vi
        vi-VN: vi

  - source: /top_speed_net/languages/server/messages.pot
    translation: /top_speed_net/languages/server/%locale%/messages.po
    skip_untranslated_files: true
    languages_mapping:
      locale:
        zh: zh-cn
        zh-CN: zh-cn
        vi: vi
        vi-VN: vi
