using TopSpeed.Protocol;
using TopSpeed.Localization;

namespace TopSpeed.Vehicles
{
    public static partial class OfficialVehicleCatalog
    {
        private static readonly float[] GtrRatios = { 3.60f, 2.32f, 1.68f, 1.31f, 1.04f, 0.89f };
        private static readonly float[] Gt3RsRatios = { 3.90f, 2.45f, 1.78f, 1.42f, 1.16f, 1.00f, 0.92f };
        private static readonly float[] Fiat500Ratios = { 3.91f, 2.24f, 1.52f, 1.15f, 1.00f };
        private static readonly float[] MiniCooperSRatios = { 3.58f, 2.10f, 1.48f, 1.17f, 0.96f, 0.88f };
        private static readonly float[] Mustang69Ratios = { 2.75f, 1.90f, 1.34f, 1.08f };
        private static readonly float[] CamryRatios = { 4.70f, 3.05f, 2.10f, 1.67f, 1.28f, 1.00f, 0.82f, 0.72f };
        private static readonly float[] AventadorRatios = { 2.95f, 1.95f, 1.46f, 1.19f, 1.00f, 0.90f, 0.84f };
        private static readonly float[] Bmw3SeriesRatios = { 5.00f, 3.20f, 2.14f, 1.72f, 1.31f, 1.00f, 0.86f, 0.78f };
        private static readonly float[] SprinterRatios = { 5.10f, 3.25f, 2.10f, 1.49f, 1.0000f, 0.8200f, 0.7300f };
        private static readonly float[] Zx10rRatios = { 2.60f, 2.00f, 1.67f, 1.45f, 1.32f, 1.24f };
        private static readonly float[] PanigaleV4Ratios = { 2.47f, 1.92f, 1.61f, 1.42f, 1.29f, 1.20f };
        private static readonly float[] R1Ratios = { 2.57f, 2.00f, 1.67f, 1.45f, 1.32f, 1.23f };
        private static readonly float[] Auto8Upshifts = { 0f, 0f, 0f, 0f, 0.18f, 0.24f, 0.30f, 0.34f };
        private static readonly float[] Auto7Upshifts = { 0f, 0f, 0f, 0f, 0.18f, 0.24f, 0.28f };
        private static readonly float[] Auto6Upshifts = { 0f, 0f, 0f, 0f, 0.20f, 0.26f };
        private static readonly TransmissionType[] AtcOnly = { TransmissionType.Atc };
        private static readonly TransmissionType[] DctOnly = { TransmissionType.Dct };
        private static readonly TransmissionType[] ManualOnly = { TransmissionType.Manual };
        private static readonly AutomaticDrivelineTuning AtcTune = AutomaticDrivelineTuning.Default;
        private static readonly AutomaticDrivelineTuning AtcHeavyTune = new AutomaticDrivelineTuning(
            new AtcDrivelineTuning(
                creepAccelKphPerSecond: 0.70f,
                launchCouplingMin: 0.24f,
                launchCouplingMax: 0.86f,
                lockSpeedKph: 44f,
                lockThrottleMin: 0.34f,
                shiftReleaseCoupling: 0.42f,
                engageRate: AutomaticDrivelineTuning.Default.Atc.EngageRate,
                disengageRate: AutomaticDrivelineTuning.Default.Atc.DisengageRate),
            AutomaticDrivelineTuning.Default.Dct,
            AutomaticDrivelineTuning.Default.Cvt);
        private static readonly AutomaticDrivelineTuning DctTune = new AutomaticDrivelineTuning(
            AutomaticDrivelineTuning.Default.Atc,
            new DctDrivelineTuning(
                launchCouplingMin: 0.34f,
                launchCouplingMax: 0.94f,
                lockSpeedKph: 16f,
                lockThrottleMin: 0.10f,
                shiftOverlapCoupling: 0.48f,
                engageRate: AutomaticDrivelineTuning.Default.Dct.EngageRate,
                disengageRate: AutomaticDrivelineTuning.Default.Dct.DisengageRate),
            AutomaticDrivelineTuning.Default.Cvt);

        public static readonly OfficialVehicleSpec[] Vehicles =
        {
            new OfficialVehicleSpec(
                CarType.Vehicle1, LocalizationService.Mark("Nissan GT-R Nismo"),
                hasWipers: 1, surfaceTractionFactor: 0.06f, topSpeed: 276.0f,
                idleFreq: 22050, topFreq: 55000, shiftFreq: 26000, gears: 6, steering: 1.20f,
                idleRpm: 900f, maxRpm: 8000f, revLimiter: 7600f, autoShiftRpm: 7600f * 0.92f, engineBraking: 0.22f,
                massKg: 1774f, drivetrainEfficiency: 0.80f, engineBrakingTorqueNm: 652f, tireGripCoefficient: 1.0f,
                peakTorqueNm: 652f, peakTorqueRpm: 3600f, idleTorqueNm: 652f * 0.3f, redlineTorqueNm: 652f * 0.6f,
                dragCoefficient: 0.26f, frontalAreaM2: 2.18f, rollingResistanceCoefficient: 0.013f, launchRpm: 2500f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.10f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(285, 35, 20), lateralGripCoefficient: 1.0f, highSpeedStability: 0.24f,
                wheelbaseM: 2.779f, maxSteerDeg: 35f, widthM: 1.895f, lengthM: 4.689f,
                powerFactor: 0.74f, gearRatios: GtrRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.94f, highSpeedSteerStartKph: 150f, highSpeedSteerFullKph: 250f,
                combinedGripPenalty: 0.70f, slipAnglePeakDeg: 8.3f, slipAngleFalloff: 1.20f,
                turnResponse: 0.96f, massSensitivity: 0.68f, downforceGripGain: 0.09f,
                cornerStiffnessFront: 1.15f, cornerStiffnessRear: 1.08f, yawInertiaScale: 1.20f, steeringCurve: 1.06f, transientDamping: 1.35f,
                primaryTransmissionType: TransmissionType.Dct, supportedTransmissionTypes: DctOnly,
                automaticTuning: DctTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(5, true, Auto6Upshifts, upshiftRpmFraction: 0.88f),
                sideAreaM2: 4.02f,
                rollingResistanceSpeedFactor: 0.0112f,
                wheelSideDragBaseN: 98f,
                wheelSideDragLinearNPerMps: 3.25f,
                coupledDrivelineDragNm: 17.0f,
                coupledDrivelineViscousDragNmPerKrpm: 6.0f,
                engineOverrunIdleLossFraction: 0.31f,
                engineBrakeTransferEfficiency: 0.66f,
                fuelTankCapacityLiters: 74f,
                engineDisplacementLiters: 3.8f),

            new OfficialVehicleSpec(
                CarType.Vehicle2, LocalizationService.Mark("Porsche 911 GT3 RS"),
                hasWipers: 1, surfaceTractionFactor: 0.07f, topSpeed: 286.0f,
                idleFreq: 22050, topFreq: 60000, shiftFreq: 35000, gears: 7, steering: 1.15f,
                idleRpm: 950f, maxRpm: 9000f, revLimiter: 8500f, autoShiftRpm: 8500f * 0.92f, engineBraking: 0.20f,
                massKg: 1450f, drivetrainEfficiency: 0.85f, engineBrakingTorqueNm: 465f, tireGripCoefficient: 1.05f,
                peakTorqueNm: 465f, peakTorqueRpm: 6250f, idleTorqueNm: 465f * 0.3f, redlineTorqueNm: 465f * 0.6f,
                dragCoefficient: 0.29f, frontalAreaM2: 2.02f, rollingResistanceCoefficient: 0.0130f, launchRpm: 3000f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.45f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(325, 30, 21), lateralGripCoefficient: 1.0f, highSpeedStability: 0.24f,
                wheelbaseM: 2.456f, maxSteerDeg: 35f, widthM: 1.852f, lengthM: 4.572f,
                powerFactor: 0.74f, gearRatios: Gt3RsRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.93f, highSpeedSteerStartKph: 150f, highSpeedSteerFullKph: 250f,
                combinedGripPenalty: 0.71f, slipAnglePeakDeg: 8.0f, slipAngleFalloff: 1.18f,
                turnResponse: 0.98f, massSensitivity: 0.66f, downforceGripGain: 0.11f,
                cornerStiffnessFront: 1.20f, cornerStiffnessRear: 1.12f, yawInertiaScale: 1.18f, steeringCurve: 1.05f, transientDamping: 1.35f,
                primaryTransmissionType: TransmissionType.Dct, supportedTransmissionTypes: DctOnly,
                automaticTuning: DctTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(5, true, Auto7Upshifts, upshiftRpmFraction: 0.85f),
                sideAreaM2: 3.62f,
                rollingResistanceSpeedFactor: 0.0105f,
                wheelSideDragBaseN: 91f,
                wheelSideDragLinearNPerMps: 3.05f,
                coupledDrivelineDragNm: 15.2f,
                coupledDrivelineViscousDragNmPerKrpm: 5.35f,
                engineOverrunIdleLossFraction: 0.25f,
                engineBrakeTransferEfficiency: 0.61f,
                fuelTankCapacityLiters: 64f,
                engineDisplacementLiters: 4.0f),

            new OfficialVehicleSpec(
                CarType.Vehicle3, LocalizationService.Mark("Fiat 500"),
                hasWipers: 1, surfaceTractionFactor: 0.035f, topSpeed: 136.0f,
                idleFreq: 6000, topFreq: 25000, shiftFreq: 19000, gears: 5, steering: 1.12f,
                idleRpm: 750f, maxRpm: 6000f, revLimiter: 5500f, autoShiftRpm: 5500f * 0.92f, engineBraking: 0.34f,
                massKg: 865f, drivetrainEfficiency: 0.88f, engineBrakingTorqueNm: 102f, tireGripCoefficient: 0.88f,
                peakTorqueNm: 102f, peakTorqueRpm: 3000f, idleTorqueNm: 102f * 0.3f, redlineTorqueNm: 102f * 0.6f,
                dragCoefficient: 0.29f, frontalAreaM2: 2.05f, rollingResistanceCoefficient: 0.013f, launchRpm: 1800f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.35f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(195, 45, 16), lateralGripCoefficient: 1.0f, highSpeedStability: 0.28f,
                wheelbaseM: 2.300f, maxSteerDeg: 35f, widthM: 1.627f, lengthM: 3.546f,
                powerFactor: 0.84f, gearRatios: Fiat500Ratios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.90f, highSpeedSteerStartKph: 120f, highSpeedSteerFullKph: 200f,
                combinedGripPenalty: 0.66f, slipAnglePeakDeg: 9.2f, slipAngleFalloff: 1.35f,
                turnResponse: 0.72f, massSensitivity: 0.82f, downforceGripGain: 0.01f,
                cornerStiffnessFront: 0.92f, cornerStiffnessRear: 0.90f, yawInertiaScale: 1.36f, steeringCurve: 1.24f, transientDamping: 2.20f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(4, true, upshiftRpmFraction: 0.84f),
                sideAreaM2: 3.78f,
                rollingResistanceSpeedFactor: 0.0104f,
                wheelSideDragBaseN: 81f,
                wheelSideDragLinearNPerMps: 2.55f,
                coupledDrivelineDragNm: 14.05f,
                coupledDrivelineViscousDragNmPerKrpm: 5.05f,
                engineOverrunIdleLossFraction: 0.32f,
                engineBrakeTransferEfficiency: 0.60f,
                fuelTankCapacityLiters: 35f,
                engineDisplacementLiters: 1.4f),

            new OfficialVehicleSpec(
                CarType.Vehicle4, LocalizationService.Mark("Mini Cooper S"),
                hasWipers: 1, surfaceTractionFactor: 0.045f, topSpeed: 198.0f,
                idleFreq: 6000, topFreq: 27000, shiftFreq: 20000, gears: 6, steering: 1.08f,
                idleRpm: 800f, maxRpm: 6500f, revLimiter: 6000f, autoShiftRpm: 6000f * 0.92f, engineBraking: 0.28f,
                massKg: 1265f, drivetrainEfficiency: 0.88f, engineBrakingTorqueNm: 280f, tireGripCoefficient: 0.95f,
                peakTorqueNm: 280f, peakTorqueRpm: 1250f, idleTorqueNm: 280f * 0.3f, redlineTorqueNm: 280f * 0.6f,
                dragCoefficient: 0.30f, frontalAreaM2: 2.08f, rollingResistanceCoefficient: 0.013f, launchRpm: 2200f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.10f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(195, 55, 16), lateralGripCoefficient: 1.0f, highSpeedStability: 0.26f,
                wheelbaseM: 2.494f, maxSteerDeg: 35f, widthM: 1.744f, lengthM: 3.876f,
                powerFactor: 0.86f, gearRatios: MiniCooperSRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.91f, highSpeedSteerStartKph: 130f, highSpeedSteerFullKph: 220f,
                combinedGripPenalty: 0.69f, slipAnglePeakDeg: 8.8f, slipAngleFalloff: 1.28f,
                turnResponse: 0.76f, massSensitivity: 0.78f, downforceGripGain: 0.03f,
                cornerStiffnessFront: 0.98f, cornerStiffnessRear: 0.95f, yawInertiaScale: 1.32f, steeringCurve: 1.20f, transientDamping: 2.05f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(5, true, Auto6Upshifts, upshiftRpmFraction: 0.86f),
                sideAreaM2: 3.88f,
                rollingResistanceSpeedFactor: 0.0115f,
                wheelSideDragBaseN: 90f,
                wheelSideDragLinearNPerMps: 3.0f,
                coupledDrivelineDragNm: 15.1f,
                coupledDrivelineViscousDragNmPerKrpm: 5.4f,
                engineOverrunIdleLossFraction: 0.34f,
                engineBrakeTransferEfficiency: 0.66f,
                fuelTankCapacityLiters: 44f,
                engineDisplacementLiters: 2.0f),

            new OfficialVehicleSpec(
                CarType.Vehicle5, LocalizationService.Mark("Ford Mustang 1969"),
                hasWipers: 1, surfaceTractionFactor: 0.04f, topSpeed: 168.0f,
                idleFreq: 6000, topFreq: 33000, shiftFreq: 27500, gears: 4, steering: 1.25f,
                idleRpm: 650f, maxRpm: 5500f, revLimiter: 5000f, autoShiftRpm: 5000f * 0.92f, engineBraking: 0.29f,
                massKg: 1440f, drivetrainEfficiency: 0.85f, engineBrakingTorqueNm: 481f, tireGripCoefficient: 0.90f,
                peakTorqueNm: 481f, peakTorqueRpm: 3000f, idleTorqueNm: 481f * 0.3f, redlineTorqueNm: 481f * 0.6f,
                dragCoefficient: 0.39f, frontalAreaM2: 2.45f, rollingResistanceCoefficient: 0.0155f, launchRpm: 2000f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 3.35f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(215, 70, 14), lateralGripCoefficient: 1.0f, highSpeedStability: 0.30f,
                wheelbaseM: 2.743f, maxSteerDeg: 35f, widthM: 1.811f, lengthM: 4.760f,
                powerFactor: 0.82f, gearRatios: Mustang69Ratios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.89f, highSpeedSteerStartKph: 125f, highSpeedSteerFullKph: 210f,
                combinedGripPenalty: 0.67f, slipAnglePeakDeg: 9.0f, slipAngleFalloff: 1.30f,
                turnResponse: 0.72f, massSensitivity: 0.80f, downforceGripGain: 0.02f,
                cornerStiffnessFront: 0.95f, cornerStiffnessRear: 0.90f, yawInertiaScale: 1.42f, steeringCurve: 1.24f, transientDamping: 2.25f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(4, false, upshiftRpmFraction: 0.84f),
                sideAreaM2: 4.55f,
                rollingResistanceSpeedFactor: 0.0125f,
                wheelSideDragBaseN: 110f,
                wheelSideDragLinearNPerMps: 3.8f,
                coupledDrivelineDragNm: 16.5f,
                coupledDrivelineViscousDragNmPerKrpm: 5.8f,
                engineOverrunIdleLossFraction: 0.41f,
                engineBrakeTransferEfficiency: 0.73f,
                fuelTankCapacityLiters: 61f,
                engineDisplacementLiters: 7.0f),

            new OfficialVehicleSpec(
                CarType.Vehicle6, LocalizationService.Mark("Toyota Camry"),
                hasWipers: 1, surfaceTractionFactor: 0.035f, topSpeed: 190.0f,
                idleFreq: 7025, topFreq: 40000, shiftFreq: 32500, gears: 8, steering: 1.20f,
                idleRpm: 700f, maxRpm: 5600f, revLimiter: 5000f, autoShiftRpm: 4600f, engineBraking: 0.28f,
                massKg: 1470f, drivetrainEfficiency: 0.88f, engineBrakingTorqueNm: 250f, tireGripCoefficient: 0.90f,
                peakTorqueNm: 250f, peakTorqueRpm: 3800f, idleTorqueNm: 250f * 0.4f, redlineTorqueNm: 250f * 0.90f,
                dragCoefficient: 0.27f, frontalAreaM2: 2.24f, rollingResistanceCoefficient: 0.0130f, launchRpm: 2000f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.60f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(215, 55, 17), lateralGripCoefficient: 1.0f, highSpeedStability: 0.32f,
                wheelbaseM: 2.825f, maxSteerDeg: 35f, widthM: 1.839f, lengthM: 4.879f,
                powerFactor: 0.72f, gearRatios: CamryRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.88f, highSpeedSteerStartKph: 120f, highSpeedSteerFullKph: 200f,
                combinedGripPenalty: 0.65f, slipAnglePeakDeg: 9.6f, slipAngleFalloff: 1.38f,
                turnResponse: 0.70f, massSensitivity: 0.86f, downforceGripGain: 0.01f,
                cornerStiffnessFront: 0.90f, cornerStiffnessRear: 0.86f, yawInertiaScale: 1.46f, steeringCurve: 1.30f, transientDamping: 2.40f,
                primaryTransmissionType: TransmissionType.Atc, supportedTransmissionTypes: AtcOnly,
                automaticTuning: AtcTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(6, true, Auto8Upshifts, upshiftRpmFraction: 0.84f, minUpshiftNetAccelerationMps2: -0.12f),
                sideAreaM2: 4.12f,
                rollingResistanceSpeedFactor: 0.0118f,
                wheelSideDragBaseN: 100f,
                wheelSideDragLinearNPerMps: 3.35f,
                coupledDrivelineDragNm: 15.7f,
                coupledDrivelineViscousDragNmPerKrpm: 5.7f,
                engineOverrunIdleLossFraction: 0.34f,
                engineBrakeTransferEfficiency: 0.67f,
                fuelTankCapacityLiters: 60f,
                engineDisplacementLiters: 2.5f),

            new OfficialVehicleSpec(
                CarType.Vehicle7, LocalizationService.Mark("Lamborghini Aventador"),
                hasWipers: 1, surfaceTractionFactor: 0.08f, topSpeed: 288.0f,
                idleFreq: 6000, topFreq: 26000, shiftFreq: 21000, gears: 7, steering: 1.28f,
                idleRpm: 1000f, maxRpm: 8500f, revLimiter: 8000f, autoShiftRpm: 8000f * 0.92f, engineBraking: 0.18f,
                massKg: 1640f, drivetrainEfficiency: 0.80f, engineBrakingTorqueNm: 720f, tireGripCoefficient: 1.05f,
                peakTorqueNm: 720f, peakTorqueRpm: 6200f, idleTorqueNm: 720f * 0.22f, redlineTorqueNm: 720f * 0.58f,
                dragCoefficient: 0.31f, frontalAreaM2: 2.06f, rollingResistanceCoefficient: 0.0137f, launchRpm: 2400f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.35f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(355, 25, 21), lateralGripCoefficient: 1.05f, highSpeedStability: 0.27f,
                wheelbaseM: 2.700f, maxSteerDeg: 25f, widthM: 2.030f, lengthM: 4.780f,
                powerFactor: 0.68f, gearRatios: AventadorRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.95f, highSpeedSteerStartKph: 155f, highSpeedSteerFullKph: 255f,
                combinedGripPenalty: 0.66f, slipAnglePeakDeg: 8.5f, slipAngleFalloff: 1.22f,
                turnResponse: 0.94f, massSensitivity: 0.56f, downforceGripGain: 0.30f,
                cornerStiffnessFront: 1.18f, cornerStiffnessRear: 1.10f, yawInertiaScale: 1.24f, steeringCurve: 1.05f, transientDamping: 1.40f,
                primaryTransmissionType: TransmissionType.Dct, supportedTransmissionTypes: DctOnly,
                automaticTuning: DctTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(5, true, Auto7Upshifts, upshiftRpmFraction: 0.90f),
                sideAreaM2: 3.92f,
                rollingResistanceSpeedFactor: 0.0118f,
                wheelSideDragBaseN: 100f,
                wheelSideDragLinearNPerMps: 3.65f,
                coupledDrivelineDragNm: 17.3f,
                coupledDrivelineViscousDragNmPerKrpm: 6.1f,
                engineOverrunIdleLossFraction: 0.28f,
                engineBrakeTransferEfficiency: 0.64f,
                fuelTankCapacityLiters: 90f,
                engineDisplacementLiters: 6.5f),

            new OfficialVehicleSpec(
                CarType.Vehicle8, LocalizationService.Mark("BMW 3 Series"),
                hasWipers: 1, surfaceTractionFactor: 0.045f, topSpeed: 230.0f,
                idleFreq: 10000, topFreq: 45000, shiftFreq: 34000, gears: 8, steering: 1.22f,
                idleRpm: 750f, maxRpm: 6500f, revLimiter: 6000f, autoShiftRpm: 6000f * 0.92f, engineBraking: 0.24f,
                massKg: 1524f, drivetrainEfficiency: 0.85f, engineBrakingTorqueNm: 346f, tireGripCoefficient: 0.93f,
                peakTorqueNm: 350f, peakTorqueRpm: 1250f, idleTorqueNm: 350f * 0.3f, redlineTorqueNm: 350f * 0.6f,
                dragCoefficient: 0.26f, frontalAreaM2: 2.18f, rollingResistanceCoefficient: 0.0130f, launchRpm: 2000f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 4.10f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(225, 50, 17), lateralGripCoefficient: 0.96f, highSpeedStability: 0.28f,
                wheelbaseM: 2.810f, maxSteerDeg: 35f, widthM: 1.811f, lengthM: 4.624f,
                powerFactor: 0.92f, gearRatios: Bmw3SeriesRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.92f, highSpeedSteerStartKph: 145f, highSpeedSteerFullKph: 240f,
                combinedGripPenalty: 0.68f, slipAnglePeakDeg: 9.0f, slipAngleFalloff: 1.30f,
                turnResponse: 0.74f, massSensitivity: 0.75f, downforceGripGain: 0.05f,
                cornerStiffnessFront: 0.98f, cornerStiffnessRear: 0.93f, yawInertiaScale: 1.38f, steeringCurve: 1.24f, transientDamping: 2.10f,
                primaryTransmissionType: TransmissionType.Atc, supportedTransmissionTypes: AtcOnly,
                automaticTuning: AtcTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(6, true, Auto8Upshifts, upshiftRpmFraction: 0.80f, minUpshiftNetAccelerationMps2: -0.20f),
                sideAreaM2: 3.98f,
                rollingResistanceSpeedFactor: 0.0116f,
                wheelSideDragBaseN: 94f,
                wheelSideDragLinearNPerMps: 3.1f,
                coupledDrivelineDragNm: 15.2f,
                coupledDrivelineViscousDragNmPerKrpm: 5.5f,
                engineOverrunIdleLossFraction: 0.31f,
                engineBrakeTransferEfficiency: 0.66f,
                fuelTankCapacityLiters: 59f,
                engineDisplacementLiters: 3.0f),

            new OfficialVehicleSpec(
                CarType.Vehicle9, LocalizationService.Mark("Mercedes Sprinter"),
                hasWipers: 1, surfaceTractionFactor: 0.02f, topSpeed: 145.0f,
                idleFreq: 22050, topFreq: 30550, shiftFreq: 22550, gears: 7, steering: 1.00f,
                idleRpm: 600f, maxRpm: 4500f, revLimiter: 4000f, autoShiftRpm: 4000f * 0.92f, engineBraking: 0.34f,
                massKg: 1970f, drivetrainEfficiency: 0.85f, engineBrakingTorqueNm: 380f, tireGripCoefficient: 0.82f,
                peakTorqueNm: 440f, peakTorqueRpm: 1400f, idleTorqueNm: 440f * 0.3f, redlineTorqueNm: 440f * 0.6f,
                dragCoefficient: 0.39f, frontalAreaM2: 3.08f, rollingResistanceCoefficient: 0.0185f, launchRpm: 1800f,
                engineInertiaKgm2: 0.24f, engineFrictionTorqueNm: 20f, drivelineCouplingRate: 12f,
                finalDriveRatio: 5.50f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(245, 75, 16), lateralGripCoefficient: 0.90f, highSpeedStability: 0.42f,
                wheelbaseM: 3.658f, maxSteerDeg: 35f, widthM: 2.019f, lengthM: 5.931f,
                powerFactor: 0.62f, gearRatios: SprinterRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.86f, highSpeedSteerStartKph: 85f, highSpeedSteerFullKph: 150f,
                combinedGripPenalty: 0.54f, slipAnglePeakDeg: 10.8f, slipAngleFalloff: 1.55f,
                turnResponse: 0.56f, massSensitivity: 0.98f, downforceGripGain: 0.01f,
                cornerStiffnessFront: 0.74f, cornerStiffnessRear: 0.66f, yawInertiaScale: 1.74f, steeringCurve: 1.32f, transientDamping: 2.90f,
                primaryTransmissionType: TransmissionType.Atc, supportedTransmissionTypes: AtcOnly,
                automaticTuning: AtcHeavyTune,
                shiftOnDemand: true,
                transmissionPolicy: Policy(5, true, Auto7Upshifts, upshiftRpmFraction: 0.72f, minUpshiftNetAccelerationMps2: -0.30f),
                sideAreaM2: 6.10f,
                rollingResistanceSpeedFactor: 0.0195f,
                wheelSideDragBaseN: 168f,
                wheelSideDragLinearNPerMps: 5.6f,
                coupledDrivelineDragNm: 22.0f,
                coupledDrivelineViscousDragNmPerKrpm: 8.0f,
                engineOverrunIdleLossFraction: 0.40f,
                engineBrakeTransferEfficiency: 0.72f,
                fuelTankCapacityLiters: 75f,
                engineDisplacementLiters: 2.1f),

            new OfficialVehicleSpec(
                CarType.Vehicle10, LocalizationService.Mark("Kawasaki Ninja ZX-10R"),
                hasWipers: 0, surfaceTractionFactor: 0.09f, topSpeed: 216.0f,
                idleFreq: 22050, topFreq: 60000, shiftFreq: 35000, gears: 6, steering: 1.08f,
                idleRpm: 1100f, maxRpm: 14000f, revLimiter: 13500f, autoShiftRpm: 13500f * 0.92f, engineBraking: 0.07f,
                massKg: 207f, drivetrainEfficiency: 0.92f, engineBrakingTorqueNm: 300f, tireGripCoefficient: 1.10f,
                peakTorqueNm: 114.9f, peakTorqueRpm: 11500f, idleTorqueNm: 114.9f * 0.36f, redlineTorqueNm: 114.9f * 0.25f,
                dragCoefficient: 0.41f, frontalAreaM2: 0.60f, rollingResistanceCoefficient: 0.0145f, launchRpm: 3900f,
                engineInertiaKgm2: 0.045f, engineFrictionTorqueNm: 5.0f, drivelineCouplingRate: 12f,
                finalDriveRatio: 6.20f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(190, 55, 17), lateralGripCoefficient: 0.76f, highSpeedStability: 0.46f,
                wheelbaseM: 1.450f, maxSteerDeg: 35f, widthM: 0.749f, lengthM: 2.085f,
                powerFactor: 1.05f, gearRatios: Zx10rRatios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.82f, highSpeedSteerStartKph: 115f, highSpeedSteerFullKph: 190f,
                combinedGripPenalty: 0.90f, slipAnglePeakDeg: 6.6f, slipAngleFalloff: 1.00f,
                turnResponse: 0.96f, massSensitivity: 0.96f, downforceGripGain: 0.03f,
                cornerStiffnessFront: 1.46f, cornerStiffnessRear: 0.96f, yawInertiaScale: 1.08f, steeringCurve: 1.05f, transientDamping: 1.40f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(6, false, upshiftRpmFraction: 0.90f),
                sideAreaM2: 0.92f,
                rollingResistanceSpeedFactor: 0.0122f,
                wheelSideDragBaseN: 22.0f,
                wheelSideDragLinearNPerMps: 0.84f,
                coupledDrivelineDragNm: 3.2f,
                coupledDrivelineViscousDragNmPerKrpm: 2.4f,
                engineOverrunIdleLossFraction: 0.22f,
                engineBrakeTransferEfficiency: 0.14f,
                fuelTankCapacityLiters: 17f,
                engineDisplacementLiters: 1.0f),

            new OfficialVehicleSpec(
                CarType.Vehicle11, LocalizationService.Mark("Ducati Panigale V4"),
                hasWipers: 0, surfaceTractionFactor: 0.10f, topSpeed: 242.0f,
                idleFreq: 22050, topFreq: 60000, shiftFreq: 35000, gears: 6, steering: 1.04f,
                idleRpm: 1200f, maxRpm: 15000f, revLimiter: 14500f, autoShiftRpm: 14500f * 0.92f, engineBraking: 0.06f,
                massKg: 191f, drivetrainEfficiency: 0.92f, engineBrakingTorqueNm: 380f, tireGripCoefficient: 1.12f,
                peakTorqueNm: 121f, peakTorqueRpm: 10000f, idleTorqueNm: 121f * 0.36f, redlineTorqueNm: 121f * 0.25f,
                dragCoefficient: 0.39f, frontalAreaM2: 0.56f, rollingResistanceCoefficient: 0.0142f, launchRpm: 3900f,
                engineInertiaKgm2: 0.042f, engineFrictionTorqueNm: 5.0f, drivelineCouplingRate: 12f,
                finalDriveRatio: 6.35f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(200, 60, 17), lateralGripCoefficient: 0.77f, highSpeedStability: 0.45f,
                wheelbaseM: 1.469f, maxSteerDeg: 35f, widthM: 0.806f, lengthM: 2.110f,
                powerFactor: 1.08f, gearRatios: PanigaleV4Ratios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.81f, highSpeedSteerStartKph: 115f, highSpeedSteerFullKph: 190f,
                combinedGripPenalty: 0.90f, slipAnglePeakDeg: 6.7f, slipAngleFalloff: 1.02f,
                turnResponse: 0.94f, massSensitivity: 0.95f, downforceGripGain: 0.03f,
                cornerStiffnessFront: 1.42f, cornerStiffnessRear: 0.98f, yawInertiaScale: 1.06f, steeringCurve: 1.06f, transientDamping: 1.38f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(5, true, Auto6Upshifts, upshiftRpmFraction: 0.90f),
                sideAreaM2: 0.88f,
                rollingResistanceSpeedFactor: 0.0117f,
                wheelSideDragBaseN: 20.5f,
                wheelSideDragLinearNPerMps: 0.81f,
                coupledDrivelineDragNm: 3.1f,
                coupledDrivelineViscousDragNmPerKrpm: 2.4f,
                engineOverrunIdleLossFraction: 0.27f,
                engineBrakeTransferEfficiency: 0.18f,
                fuelTankCapacityLiters: 16f,
                engineDisplacementLiters: 1.1f),

            new OfficialVehicleSpec(
                CarType.Vehicle12, LocalizationService.Mark("Yamaha YZF-R1"),
                hasWipers: 0, surfaceTractionFactor: 0.085f, topSpeed: 219.0f,
                idleFreq: 22050, topFreq: 27550, shiftFreq: 23550, gears: 6, steering: 1.10f,
                idleRpm: 1100f, maxRpm: 14500f, revLimiter: 14000f, autoShiftRpm: 14000f * 0.92f, engineBraking: 0.07f,
                massKg: 201f, drivetrainEfficiency: 0.92f, engineBrakingTorqueNm: 315f, tireGripCoefficient: 1.10f,
                peakTorqueNm: 112.4f, peakTorqueRpm: 11500f, idleTorqueNm: 112.4f * 0.36f, redlineTorqueNm: 112.4f * 0.25f,
                dragCoefficient: 0.40f, frontalAreaM2: 0.57f, rollingResistanceCoefficient: 0.0144f, launchRpm: 3900f,
                engineInertiaKgm2: 0.044f, engineFrictionTorqueNm: 5.0f, drivelineCouplingRate: 12f,
                finalDriveRatio: 6.25f, reverseMaxSpeedKph: 35f, reversePowerFactor: 0.55f, reverseGearRatio: 3.2f,
                tireCircumferenceM: TireCircumferenceM(190, 55, 17), lateralGripCoefficient: 0.75f, highSpeedStability: 0.47f,
                wheelbaseM: 1.405f, maxSteerDeg: 35f, widthM: 0.690f, lengthM: 2.055f,
                powerFactor: 1.03f, gearRatios: R1Ratios!, brakeStrength: 1.0f,
                highSpeedSteerGain: 0.82f, highSpeedSteerStartKph: 115f, highSpeedSteerFullKph: 190f,
                combinedGripPenalty: 0.91f, slipAnglePeakDeg: 6.5f, slipAngleFalloff: 1.01f,
                turnResponse: 0.95f, massSensitivity: 0.95f, downforceGripGain: 0.03f,
                cornerStiffnessFront: 1.44f, cornerStiffnessRear: 0.95f, yawInertiaScale: 1.08f, steeringCurve: 1.05f, transientDamping: 1.40f,
                primaryTransmissionType: TransmissionType.Manual, supportedTransmissionTypes: ManualOnly,
                transmissionPolicy: Policy(5, true, Auto6Upshifts, upshiftRpmFraction: 0.88f),
                sideAreaM2: 0.90f,
                rollingResistanceSpeedFactor: 0.0120f,
                wheelSideDragBaseN: 21.5f,
                wheelSideDragLinearNPerMps: 0.82f,
                coupledDrivelineDragNm: 3.1f,
                coupledDrivelineViscousDragNmPerKrpm: 2.35f,
                engineOverrunIdleLossFraction: 0.22f,
                engineBrakeTransferEfficiency: 0.15f,
                fuelTankCapacityLiters: 17f,
                engineDisplacementLiters: 1.0f)
        };

    }
}



