using System;
using TopSpeed.Data;
using TopSpeed.Drive.Session.Audio;
using TopSpeed.Input;
using TopSpeed.Physics.Fuel;
using TopSpeed.Physics.Powertrain;
using TopSpeed.Protocol;
using TopSpeed.Tracks;
using TopSpeed.Vehicles.Audio;
using TopSpeed.Vehicles.Core;
using TopSpeed.Vehicles.Events;
using TopSpeed.Vehicles.Physics;
using TS.Audio;
using TopSpeed.Input.Devices.Vibration;

namespace TopSpeed.Vehicles
{
    internal partial class Car
    {
        private const int MaxSurfaceFreq = 100000;
        private const float CrashVibrationSeconds = 1.5f;
        private const float BumpVibrationSeconds = 0.2f;
        private const float EngineShutdownFadeSeconds = 0.12f;
        private const int ReverseGear = -1;
        private const int NeutralGear = 0;
        private const int FirstForwardGear = 1;
        private const float ReverseShiftMaxSpeedKmh = 15.0f;

        private bool _stickReleased = true;

        private readonly Track _track;
        private readonly DriveSettings _settings;
        private readonly Func<float> _currentTime;
        private readonly Func<bool> _started;
        private readonly EventQueue _events;
        private readonly Processor _eventProcessor;
        private readonly IFlow _audioFlow;
        private readonly CarRuntimeContext _runtimeContext;
        private readonly IVibrationDevice? _vibration;
        private readonly PlayerVehicleAudio _raceAudio;

        private IModel _physicsModel;

        private CarState _state;
        private TrackSurface _surface;
        private int _gear;
        private float _speed;
        private float _positionX;
        private float _positionY;
        private bool _manualTransmission;
        private bool _engineStalled;
        private bool _backfirePlayed;
        private int _hasWipers;
        private int _switchingGear;
        private float _autoShiftCooldown;
        private CarType _carType;
        private ICarListener? _listener;
        private string? _customFile;
        private bool _userDefined;

        private float _surfaceTractionFactor;
        private float _topSpeed;
        private float _massKg;
        private float _baseMassKgAtFullTank;
        private float _drivetrainEfficiency;
        private float _engineBrakingTorqueNm;
        private float _tireGripCoefficient;
        private float _brakeStrength;
        private float _wheelRadiusM;
        private float _engineBraking;
        private float _idleRpm;
        private float _revLimiter;
        private float _finalDriveRatio;
        private float _reverseMaxSpeedKph;
        private float _reversePowerFactor;
        private float _reverseGearRatio;
        private float _powerFactor;
        private float _peakTorqueNm;
        private float _peakTorqueRpm;
        private float _idleTorqueNm;
        private float _redlineTorqueNm;
        private float _dragCoefficient;
        private float _frontalAreaM2;
        private float _sideAreaM2;
        private float _rollingResistanceCoefficient;
        private float _rollingResistanceSpeedFactor;
        private float _wheelSideDragBaseN;
        private float _wheelSideDragLinearNPerMps;
        private float _launchRpm;
        private float _coupledDrivelineDragNm;
        private float _coupledDrivelineViscousDragNmPerKrpm;
        private float _engineInertiaKgm2;
        private float _engineFrictionTorqueNm;
        private float _drivelineCouplingRate;
        private float _lastDriveRpm;
        private float _drivelineCouplingFactor = 1f;
        private float _stallTimer;
        private float _cvtRatio;
        private float _effectiveDriveRatioOverride;
        private float _automaticCreepAccelMps2;
        private float _lateralGripCoefficient;
        private float _highSpeedStability;
        private float _wheelbaseM;
        private float _maxSteerDeg;
        private float _highSpeedSteerGain;
        private float _highSpeedSteerStartKph;
        private float _highSpeedSteerFullKph;
        private float _combinedGripPenalty;
        private float _slipAnglePeakDeg;
        private float _slipAngleFalloff;
        private float _turnResponse;
        private float _massSensitivity;
        private float _downforceGripGain;
        private float _cornerStiffnessFront;
        private float _cornerStiffnessRear;
        private float _yawInertiaScale;
        private float _steeringCurve;
        private float _transientDamping;
        private float _widthM;
        private float _lengthM;
        private int _idleFreq;
        private int _topFreq;
        private int _shiftFreq;
        private float _pitchCurveExponent;
        private int _gears;
        private float _steering;
        private float _thrust;
        private int _prevFrequency;
        private int _frequency;
        private int _prevBrakeFrequency;
        private int _brakeFrequency;
        private int _prevSurfaceFrequency;
        private int _surfaceFrequency;
        private float _laneWidth;
        private float _relPos;
        private int _panPos;
        private int _currentSteering;
        private int _currentThrottle;
        private int _currentBrake;
        private float _currentSurfaceTractionFactor;
        private float _currentSurfaceBrakeFactor;
        private float _currentSurfaceRollingResistanceFactor;
        private float _currentSurfaceLateralMultiplier;
        private float _speedDiff;
        private int _factor1;
        private int _frame;
        private float _prevThrottleVolume;
        private float _throttleVolume;
        private float _lastAudioX;
        private float _lastAudioY;
        private bool _audioInitialized;
        private float _lastAudioElapsed;
        private float _lateralVelocityMps;
        private float _yawRateRad;
        private float _fuelTankCapacityLiters;
        private float _fuelEngineDisplacementLiters;
        private float _fuelBurnLitersPerHour;
        private float _fuelEstimatedRangeMeters;
        private float _fuelEfficiencyLitersPer100Km;
        private float _fuelEfficiencyMpg;
        private bool _fuelLow;
        private bool _fuelEmpty;
        private float _fuelPowerScale = 1f;
        private float _fuelWarningPulseTimerSeconds;

        private Source _soundEngine = default!;
        private Source? _soundThrottle;
        private Source _soundHorn = default!;
        private Source _soundStart = default!;
        private Source? _soundStop;
        private Source _soundBrake = default!;
        private Source _soundCrash = default!;
        private Source[] _soundCrashVariants = Array.Empty<Source>();
        private Source _soundMiniCrash = default!;
        private Source _soundAsphalt = default!;
        private Source _soundGravel = default!;
        private Source _soundWater = default!;
        private Source _soundSand = default!;
        private Source _soundSnow = default!;
        private Source? _soundWipers;
        private Source _soundBump = default!;
        private Source _soundBadSwitch = default!;
        private Source _soundFuelWarning = default!;
        private Source? _soundBackfire;
        private Source[] _soundBackfireVariants = Array.Empty<Source>();
        private int _lastPlayerEngineVolumePercent = -1;
        private int _lastPlayerEventsVolumePercent = -1;
        private int _lastSurfaceLoopVolumePercent = -1;

        private EngineModel _engine = default!;
        private Config _powertrainConfiguration = default!;
        private FuelConfig _fuelConfiguration = new FuelConfig(FuelDefaults.DefaultTankCapacityLiters, FuelDefaults.DefaultEngineDisplacementLiters);
        private FuelRuntimeState _fuelState = new FuelRuntimeState(FuelDefaults.DefaultTankCapacityLiters, 0f);
        private TransmissionPolicy _transmissionPolicy = TransmissionPolicy.Default;
        private AutomaticDrivelineTuning _automaticTuning = AutomaticDrivelineTuning.Default;
        private TransmissionType _primaryTransmissionType = TransmissionType.Atc;
        private TransmissionType[] _supportedTransmissionTypes = new[] { TransmissionType.Atc };
        private TransmissionType _activeTransmissionType = TransmissionType.Atc;
        private bool _shiftOnDemandSupported;
        private bool _shiftOnDemandEnabled;
        private DrivelineState _drivelineState = DrivelineState.Locked;
        private EngineCombustionState _combustionState = EngineCombustionState.Off;
        private EngineRotationState _engineRotationState = EngineRotationState.Stopped;
    }
}



